name: airvana
description: A minimalist breathing app with customizable presets and statistics

environment:
  sdk: ">=2.19.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5
  shared_preferences: ^2.2.2
  flutter_local_notifications: ^16.1.0
  just_audio: ^0.9.36
  intl: ^0.18.1
  flutter_svg: ^2.0.8
  path_provider: ^2.1.1
  timezone: ^0.9.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/sounds/
    - assets/images/